<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rata2_5dan10</name>
   <tag></tag>
   <elementGuidId>6b429f07-200b-4786-a3cc-698279e17bac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;solutionFinder&quot;]/section[3]/div[3]/div/div[1]/div/div/span/div/div/span/span/ul/li[4]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
